spring:
  profiles:
    active: ${SPRING_PROFILE:dev}

  jpa:
    open-in-view: false
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  cache:
    type: caffeine
    caffeine:
      spec: maximumSize=500,expireAfterWrite=5m

  jackson:
    serialization:
      write-dates-as-timestamps: false

server:
  port: 8080

jwt:
  expiration: 1800000
  refresh-expiration: 2592000000
